---
- hosts: all
  become: true

  environment:
    DB_PASS: "{{db_pass}}"

  tasks:
    - name: install depndencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Install Docker Module for Python
      pip:
        name: "{{item}}"
      loop:
        - docker
        - docker-compose

    - name: make sure docker is enabled
      service:
        name: docker
        state: started
        enabled: yes


    - name: adding existing user '{{ user }}' to group docker
      user:
        name: '{{ user }}'
        groups: docker
        append: yes

    - name: create database volume directory
      file:
        path: /var/lib/mysql
        state: directory

    - name: create deployment directory
      file:
        path: /var/sites/current_release
        state: directory

    - name: copy docker compose file
      copy:
        src: "{{playbook_dir}}/../docker-compose.yml"
        dest: /var/sites/current_release

    - name: create docker images
      community.docker.docker_compose:
        project_src: /var/sites/current_release
        pull: true
      register: output
