pipeline {
    agent any
    triggers {
      githubPush()
    }
    environment {
      IMAGE_NAME = 'nikpolik/devops-todo'
      DOCKER_CRED = credentials('nikpolik-dockerhub')
    }
    stages {
        stage('Build Web App') {
          steps {
            echo 'Builing War file...'
            sh 'mvn clean package'
          }
        }
        stage('Build Login') {
          steps {
            echo 'Login in to dockerhub...'
            sh "docker login -u ${DOCKER_CRED_USR} -p ${DOCKER_CRED_PSW}"
          }
        }
        stage('Build Docker Images') {
          steps {
            echo 'Building webapp Image...'
            sh "docker build -f ./devops/Dockerfile -t ${IMAGE_NAME}:${BUILD_NUMBER} ."
          }
        }
        stage('Publishing Image') {
          echo 'Publishing web app image...'
          sh "docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${IMAGE_NAME}:latest"
          sh "docker push ${IMAGE_NAME}"
        }
        stage('Connecting to ansible') {
        }
    }
    post {
      success {
        echo 'Deploy Succeeded'
      }
    }
}
