pipeline {
    agent any
    triggers {
      githubPush()
    }
    environment {
      IMAGE_NAME = 'nikpolik/devops-todo'
      DOCKER_CRED = credentials('docker')
      PRODUCTION_VM_CRED = credentials('ubuntu-production-credentials')
    }
    stages {
        stage('Build Web App') {
          steps {
            echo 'Builing War file...'
            sh 'mvn clean package'
          }
        }
        stage('Build Login') {
          steps {
            echo 'Login in to dockerhub...'
            sh "docker login -u ${DOCKER_CRED_USR} -p ${DOCKER_CRED_PSW}"
          }
        }
        stage('Build Docker Images') {
          steps {
            echo 'Building webapp Image...'
            sh "docker build -f ./devops/Dockerfile -t ${IMAGE_NAME}:${BUILD_NUMBER} ."
          }
        }
        stage('Publishing Image') {
          steps {
            echo 'Publishing web app image...'
            sh "docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${IMAGE_NAME}:latest"
            sh "docker push ${IMAGE_NAME}"
          }
        }
        stage('Production VM setup') {
          setps {
            echo 'Building production VM'
            dir('./terraform') {
              sh """
                terraform apply -target=module.producton-vm \
                  -var='vm_username="${PRODUCTION_VM_CRED_USR}"' \
                  -var='vm_password="${PRODUCTION_VM_CRED_PSW}"'
              """
              PRODUCTION_VM_IP = sh 'terraform output -json production_ip_adress | jq -r'
              echo "${PRODUCTION_VM_IP}"
            }
          }
        }
    }
    post {
      success {
        echo 'Deploy Succeeded'
      }
    }
}
